# [dein_lazy.toml]

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_cmd = 'Denite'
hook_add = '''
let g:denite_enable_start_insert=1
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'
on_path ='.*'

[[plugins]]
repo = 'tpope/vim-endwise'
