# [dein_lazy.toml]

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_cmd = 'Denite'
hook_add = '''
let g:denite_enable_start_insert=1
'''
hook_post_source = '''
call denite#custom#option('default', 'prompt', '>')
call denite#custom#source('file_rec', 'matchers', ['matcher_fuzzy', 'matcher_ignore_globs'])
call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
  \ [
  \ '.git/', '.DS_Store'
  \ ]
) 
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_post_source = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
if = 'has("nvim")'
on_source = 'denite.nvim'
on_path ='.*'

[[plugins]]
repo = 'tpope/vim-endwise'
